import Footer from "@/Components/Footer";
import Header from "@/Components/Header";
import store from "@/store/store";
import "@/styles/globals.css";
import Head from "next/head";
import { Provider } from "react-redux";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        {" "}
        {/*Contains several meta tags, which provides information about the web page to search 
      engines and adjust layout for different devices */}
        <title>Sam Store LLC</title>
        <meta name="description" content="Generated by create next app" />
        {/*Meta tag is an html element that provides information about a web page. It includes a head section of an html and is not displayed
        on the actual webage. The above code indicates that the webpage was generated by next app and is typically
        used by search engines to provide a summary of the page in result */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/*The above tag specifies how the web page should be displayed on different devices with varying screensize
        -The viewport tag tells the browser to adjust the page layout to fit the width of the device screen.
        - Inital-scale attribute sets the intial zoom level of hte web page which here is default(no zoom in or out) */}
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&family=Playfair+Display&family=Quicksand:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Provider store={store}>
        {" "}
        {/*Provider component makes the Redux store available to any nested components that
      need to access the Redux store */}
        <Header />
        <Component {...pageProps} />
        <Footer />
      </Provider>
    </>
  );
}
